In [ ]:
import pandas as pd
import seaborn as sns

In [2]:
df = pd.read_parquet('/mnt/c/mldata/aliccp/train_processed/')

In [ ]:
df

In [5]:
len(df['item_id'].unique())

3156553

In [12]:
df['counter'] = 1
df_agg = df[['item_id','counter']].groupby('item_id').count()

In [19]:
df_agg = df_agg[df_agg['counter']>10]
df_agg

counter
item_id         
3964450       64
3964460       11
3964468       13
3964536       92
3964547       35
...          ...
8312940       12
8312950       22
8312976       88
8313039       43
8313058       11

[497324 rows x 1 columns]

In [20]:
pd.merge(df_agg, df, on=['item_id', 'item_id'], how='left')

item_id  counter_x item_intention item_brand position item_category  \
0         3964450         64        9101301    9134429  9351665       8317887   
1         3964450         64        9104586    9134429  9351665       8317887   
2         3964450         64        9104586    9134429  9351665       8317887   
3         3964450         64        9029481    9134429  9351665       8317887   
4         3964450         64        9104586    9134429  9351667       8317887   
...           ...        ...            ...        ...      ...           ...   
35440267  8313058         11        9067825    9151341  9351665       8313470   
35440268  8313058         11        9103788    9151341  9351665       8313470   
35440269  8313058         11        9032778    9151341  9351666       8313470   
35440270  8313058         11        9067825    9151341  9351666       8313470   
35440271  8313058         11        9075520    9151341  9351665       8313470   

         item_shop user_item_categories user_profile user_group  ...  \
0          8859369                 None      3438738    3438757  ...   
1          8859369              9356068      3438669    3438761  ...   
2          8859369                 None      3438658    3438763  ...   
3          8859369                 None      3438658    3438763  ...   
4          8859369              9356068      3438658    3438758  ...   
...            ...                  ...          ...        ...  ...   
35440267   8880367              9352046      3438658    3438763  ...   
35440268   8880367              9352046      3438658    3438760  ...   
35440269   8880367              9352046      3438671    3438761  ...   
35440270   8880367                 None      3438658    3438762  ...   
35440271   8880367                 None         None       None  ...   

         user_brands user_categories user_shops click conversion  \
0            3485530          446478    3430237     0          0   
1            3749962          446478    2119670     0          0   
2            3770653          449924    2393206     0          0   
3            3770653          449924    2393206     0          0   
4            3754574          445379    2407992     1          0   
...              ...             ...        ...   ...        ...   
35440267     3735142          451092    1127915     0          0   
35440268     3764748          451536    1127915     0          0   
35440269     3752199          449924    3394963     0          0   
35440270     3797148          445232    2973476     0          0   
35440271     3702298          451036    1930894     0          0   

         user_item_shops user_item_brands user_item_intentions  \
0                9725249          9844777                 None   
1                9725249          9844777                 None   
2                   None             None                 None   
3                   None             None                 None   
4                9725249          9844777                 None   
...                  ...              ...                  ...   
35440267            None          9857109                 None   
35440268            None          9857109                 None   
35440269            None          9857109             10053486   
35440270            None          9857109                 None   
35440271            None          9857109                 None   

         user_consumption counter_y  
0                 3438778         1  
1                 3438778         1  
2                    None         1  
3                    None         1  
4                    None         1  
...                   ...       ...  
35440267             None         1  
35440268             None         1  
35440269          3438778         1  
35440270             None         1  
35440271             None         1  

[35440272 rows x 27 columns]

In [2]:

# Load it back; can also be done in TensorFlow Serving.
loaded = tf.saved_model.load("index")


2023-02-28 14:24:51.398810: I tensorflow/compiler/xla/stream_executor/cuda/cuda_gpu_executor.cc:967] could not open file to read NUMA node: /sys/bus/pci/devices/0000:01:00.0/numa_node
Your kernel may have been built without NUMA support.
2023-02-28 14:24:51.434601: W tensorflow/compiler/xla/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcudnn.so.8'; dlerror: libcudnn.so.8: cannot open shared object file: No such file or directory
2023-02-28 14:24:51.434624: W tensorflow/core/common_runtime/gpu/gpu_device.cc:1934] Cannot dlopen some GPU libraries. Please make sure the missing libraries mentioned above are installed properly if you would like to use GPU. Follow the guide at https://www.tensorflow.org/install/gpu for how to download and setup the required libraries for your platform.
Skipping registering GPU devices...
2023-02-28 14:24:51.435155: I tensorflow/core/platform/cpu_feature_guard.cc:193] This TensorFlow binary is optimized with oneAPI Deep

In [7]:
loaded([5000])


(<tf.Tensor: shape=(1, 50), dtype=float32, numpy=
 array([[0.02848982, 0.02848982, 0.02848982, 0.02848982, 0.02848982,
         0.02848982, 0.02848982, 0.02819037, 0.02819037, 0.02819037,
         0.02819037, 0.02819037, 0.02819037, 0.02819037, 0.02819037,
         0.02819037, 0.02819037, 0.02819037, 0.02819037, 0.02819037,
         0.02819037, 0.02819037, 0.02819037, 0.02819037, 0.02819037,
         0.02819037, 0.02819037, 0.02819037, 0.02819037, 0.02819037,
         0.02819037, 0.02819037, 0.02819037, 0.02819037, 0.02819037,
         0.02819037, 0.02819037, 0.02819037, 0.02780354, 0.02780354,
         0.02780354, 0.02780354, 0.02780354, 0.02780354, 0.02780354,
         0.02780354, 0.02780354, 0.02780354, 0.02780354, 0.02780354]],
       dtype=float32)>,
 <tf.Tensor: shape=(1, 50), dtype=int64, numpy=
 array([[5131832, 5131832, 5131832, 5131832, 5131832, 5131832, 5131832,
         7569337, 7569337, 7569337, 7569337, 7569337, 7569337, 7569337,
         7569337, 7569337, 7569337, 756933

In [19]:
loaded.query_model.([42])

TypeError: '_UserObject' object is not subscriptable